# Generated by Django 5.1 on 2024-10-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation_app.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation_app.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='renter', to='reservation_app.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant', to='reservation_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
