# Generated by Django 5.1 on 2024-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=250)),
                ('year', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('damage', models.TextField()),
                ('mileage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='clients_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.FloatField(default=0),
        ),
    ]
