# Generated by Django 5.1 on 2024-10-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_car_location_company_clients_per_month_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation_app.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(to='reservation_app.car'),
        ),
    ]
