# Generated by Django 5.1.2 on 2024-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0005_location_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='image',
            new_name='city_image',
        ),
        migrations.AddField(
            model_name='location',
            name='country_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='location',
            name='region_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
