# Generated by Django 5.1.2 on 2024-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0006_rename_image_location_city_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default="0001-01-01"),
            preserve_default=False,
        ),
    ]
